name: Check HTTP Connectivity

on: push  # Allows manual trigger

jobs:
  check-connectivity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          sudo apt-get update 
          sudo apt-get install -y wget

      - name: Run HTTP connectivity check
        run: python3 main.py
