name: Check HTTP Connectivity

on:
  workflow_dispatch:  # Allows manual trigger

jobs:
  check-connectivity:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Install dependencies
        run: |
          apt-get update && apt-get install -y wget && apt-get install -y os && apt-get install -y subprocess

      - name: Run HTTP connectivity check
        run: python3 main.py
