name: Check Multiple Host Env Vars in Docker (Self-Hosted)

on:
  workflow_dispatch:

jobs:
  run-in-self-hosted:
    runs-on: self-hosted  # Your local machine runner

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build -t env-checker .

      - name: Run Docker container with multiple host env vars
        run: |
          docker run --rm \
            -e ENV_VAR1 \
            -e ENV_VAR2 \
            env-checker
